require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` by adding a `# flipper_enabled=false` flag
# to disable Flipper in release mode.
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TourManagerMobileApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # React Native Vector Icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # React Native Gesture Handler
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  # React Native Reanimated
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # React Native Safe Area Context
  pod 'RNSafeAreaContext', :path => '../node_modules/react-native-safe-area-context'

  # React Native Screens
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  # Firebase
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAuth', :modular_headers => true
  pod 'FirebaseFirestore', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true

  # Location Services
  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  # Camera and Image Picker
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # File System
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  # SQLite
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  # Permissions
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  # Push Notifications
  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  # Async Storage
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  # NetInfo
  pod 'RNCNetInfo', :path => '../node_modules/@react-native-community/netinfo'

  # DateTimePicker
  pod 'RNCDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  # Document Picker
  pod 'RNDocumentPicker', :path => '../node_modules/react-native-document-picker'

  # Share
  pod 'RNShare', :path => '../node_modules/react-native-share'

  # Linear Gradient
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # SVG
  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  # Calendars
  pod 'RNCalendars', :path => '../node_modules/react-native-calendars'

  # Contacts
  pod 'RNContacts', :path => '../node_modules/react-native-contacts'

  # Keychain
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'

  # Camera Roll
  pod 'RNCCameraRoll', :path => '../node_modules/@react-native-camera-roll/camera-roll'

  # Fast Image
  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  # Encrypted Storage
  pod 'RNEncryptedStorage', :path => '../node_modules/react-native-encrypted-storage'

  target 'TourManagerMobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    # Fix for XCode 14.3
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end
  end
end